name: PR Tests

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'deps.edn'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      stripe-mock:
        image: stripe/stripe-mock:latest
        ports:
          - 12111:12111
          - 12112:12112
    
    container: 
      image: clojure:temurin-17-tools-deps
      env:
        STRIPE_TEST_API_KEY: ${{ secrets.STRIPE_TEST_API_KEY }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
        restore-keys: ${{ runner.os }}-deps-
    
    - name: Run single test file
      run: clj -M:test -n stripe-clojure.mock.charges-test