name: PR Tests

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'deps.edn'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      stripe-mock:
        image: stripe/stripe-mock:latest
        ports:
          - 12111:12111
          - 12112:12112
    
    container: 
      image: clojure:temurin-17-tools-deps
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
        restore-keys: ${{ runner.os }}-deps-
    
    - name: Verify stripe-mock
      run: |
        for i in {1..30}; do
          if curl -s -f http://stripe-mock:12111/v1/charges -H "Authorization: Bearer ${{ secrets.STRIPE_API_KEY }}"; then
            echo "stripe-mock is ready"
            exit 0
          fi
          echo "Waiting for stripe-mock... attempt $i"
          sleep 1
        done
        echo "stripe-mock failed to start"
        exit 1
    
    - name: Run single test file
      env:
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      run: |
        # Run only one test file
        clj -M:test -v stripe-clojure.charge-test